import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import { LANDING_TOPICS, getLandingTopicBySlug } from '@/lib/landing/topics';
import { theoryDocs } from '@/data/learn/theory';
import { getTheoryTracks } from '@/data/learn/theory/tracks';
import { TopicLandingPage } from '@/components/topics/TopicLandingPage';
import { BreadcrumbJsonLd, CourseJsonLd } from '@/lib/seo/jsonLd';

interface TopicLandingRouteProps {
  params: { slug: string };
}

const TOPIC_KEYWORDS: Record<string, string[]> = {
  airflow: [
    'apache airflow course',
    'airflow dag tutorial',
    'airflow for data engineers',
    'airflow scheduling',
    'orchestration tools',
  ],
  fabric: [
    'microsoft fabric course',
    'onelake tutorial',
    'fabric lakehouse',
    'fabric pipelines',
    'fabric for data engineers',
  ],
  pyspark: [
    'pyspark course',
    'pyspark for data engineers',
    'spark catalyst optimizer',
    'pyspark partitioning',
    'distributed data engineering',
  ],
  sql: [
    'sql for data engineering',
    'sql for data engineers',
    'sql query optimization',
    'dimensional modeling',
    'warehouse sql tutorial',
  ],
  python: [
    'python for data engineering',
    'python for data engineers',
    'pydantic tutorial',
    'polars dataframes',
    'async python data pipelines',
  ],
};

export default function Page({ params }: TopicLandingRouteProps) {
  const topic = getLandingTopicBySlug(params.slug);
  if (!topic) {
    notFound();
  }

  const doc = theoryDocs[topic.topicId];
  const tracks = doc ? getTheoryTracks(doc) : [];
  const totalMinutes = tracks.reduce((sum, t) => sum + t.totalMinutes, 0);

  const url = `https://stablegrid.io/topics/${topic.slug}`;
  const breadcrumbItems = [
    { name: 'Home', url: '/' },
    { name: 'Topics', url: '/topics' },
    { name: topic.name, url: `/topics/${topic.slug}` },
  ];

  return (
    <>
      <BreadcrumbJsonLd items={breadcrumbItems} />
      <CourseJsonLd
        name={topic.name}
        description={topic.description}
        url={url}
        totalMinutes={totalMinutes > 0 ? totalMinutes : undefined}
      />
      <TopicLandingPage topic={topic} tracks={tracks} />
    </>
  );
}

export function generateStaticParams() {
  return LANDING_TOPICS.map((t) => ({ slug: t.slug }));
}

export function generateMetadata({
  params,
}: TopicLandingRouteProps): Metadata {
  const topic = getLandingTopicBySlug(params.slug);
  if (!topic) {
    return {
      title: 'Topic not found',
      robots: { index: false, follow: false },
    };
  }

  const canonical = `/topics/${topic.slug}`;
  const fullUrl = `https://stablegrid.io${canonical}`;
  const title = `${topic.name} — Junior to Senior on StableGrid`;
  const ogTitle = `${topic.name} — Junior to Senior`;

  return {
    title,
    description: topic.description,
    keywords: TOPIC_KEYWORDS[topic.slug],
    alternates: {
      canonical,
      languages: {
        'en-US': canonical,
        'x-default': canonical,
      },
    },
    openGraph: {
      type: 'website',
      url: fullUrl,
      siteName: 'StableGrid',
      title: ogTitle,
      description: topic.description,
      // Per-topic image is generated by app/topics/[slug]/opengraph-image.tsx
    },
    twitter: {
      card: 'summary_large_image',
      title: ogTitle,
      description: topic.description,
      // Twitter falls back to the opengraph-image automatically.
    },
  };
}
